"""Shared Indian Government Tender Catalog for Search and Listing Services."""

CATALOG_TENDERS = [
    {
        "id": "gem-2026-001",
        "title": "Supply & Installation of Solar PV Power Systems 500kW",
        "ministry": "Ministry of New and Renewable Energy",
        "department": "Solar Energy Division",
        "organisation": "IREDA / SECI",
        "state": "Delhi",
        "categories": ["Renewable Energy", "Solar", "Electrical"],
        "estimated_cost_lakhs": 250.0,
        "emd_lakhs": 5.0,
        "submission_deadline": "2026-08-30T17:00:00",
        "status": "active",
        "source": "GeM",
        "msme_eligible": True,
        "startup_eligible": True,
        "source_url": "https://gem.gov.in/tenders/gem-2026-001",
        "source_tender_id": "GEM/2026/B/882739",
        "ai_summary": "Procurement of 500kW Rooftop Solar Systems under Make in India Class-I with MSME EMD waiver.",
        "published_at": "2026-08-01T10:00:00",
        "procurement_method": "Open Tender",
    },
    {
        "id": "cppp-2026-002",
        "title": "Development of Enterprise AI Chatbot & RAG Decision Engine",
        "ministry": "Ministry of Electronics and Information Technology",
        "department": "Digital India Corporation",
        "organisation": "NIC / MeitY",
        "state": "Maharashtra",
        "categories": ["IT", "AI", "Software"],
        "estimated_cost_lakhs": 180.0,
        "emd_lakhs": 3.6,
        "submission_deadline": "2026-09-15T15:00:00",
        "status": "active",
        "source": "CPPP",
        "msme_eligible": True,
        "startup_eligible": True,
        "source_url": "https://eprocure.gov.in/eprocure/app",
        "source_tender_id": "2026_MEITY_774920_1",
        "ai_summary": "Multi-agent AI platform implementation for government e-governance workflows.",
        "published_at": "2026-08-02T12:00:00",
        "procurement_method": "QCBS",
    },
    {
        "id": "ireps-2026-003",
        "title": "Supply of Smart Railway Track Inspection & IoT Sensors",
        "ministry": "Ministry of Railways",
        "department": "Railway Board / Northern Railway",
        "organisation": "Indian Railways",
        "state": "Uttar Pradesh",
        "categories": ["Railways", "Mobility", "IoT", "Infrastructure"],
        "estimated_cost_lakhs": 420.0,
        "emd_lakhs": 8.4,
        "submission_deadline": "2026-09-05T18:00:00",
        "status": "active",
        "source": "IREPS",
        "msme_eligible": False,
        "startup_eligible": True,
        "source_url": "https://ireps.gov.in",
        "source_tender_id": "NR-MECH-2026-992",
        "ai_summary": "IoT-based track monitoring and real-time fault detection for high speed corridors.",
        "published_at": "2026-08-01T09:00:00",
        "procurement_method": "Open Tender",
    },
    {
        "id": "drdo-2026-004",
        "title": "Autonomous Surveillance Drone Fleet & Thermal Imaging Payload",
        "ministry": "Ministry of Defence",
        "department": "Defence Research and Development Organisation",
        "organisation": "DRDO / Aeronautical Development Establishment",
        "state": "Karnataka",
        "categories": ["Defence", "Drone", "Aerospace", "AI"],
        "estimated_cost_lakhs": 850.0,
        "emd_lakhs": 17.0,
        "submission_deadline": "2026-09-20T16:00:00",
        "status": "active",
        "source": "Defence",
        "msme_eligible": True,
        "startup_eligible": True,
        "source_url": "https://drdo.gov.in/tenders",
        "source_tender_id": "DRDO/ADE/2026/UAV-04",
        "ai_summary": "Procurement of tactical autonomous VTOL drones with AI edge payload for border surveillance.",
        "published_at": "2026-08-02T11:00:00",
        "procurement_method": "QCBS",
    },
    {
        "id": "hal-2026-005",
        "title": "Precision Avionics Components & Machined Titanium Assemblies",
        "ministry": "Ministry of Defence",
        "department": "Defence Production",
        "organisation": "Hindustan Aeronautics Limited (HAL)",
        "state": "Karnataka",
        "categories": ["Defence", "Aerospace", "Manufacturing"],
        "estimated_cost_lakhs": 1200.0,
        "emd_lakhs": 24.0,
        "submission_deadline": "2026-09-28T14:00:00",
        "status": "active",
        "source": "HAL",
        "msme_eligible": True,
        "startup_eligible": False,
        "source_url": "https://hal-india.co.in/tenders",
        "source_tender_id": "HAL/LCA/COMP/2026/89",
        "ai_summary": "Precision aerospace titanium structural sub-assemblies for Tejas Mk1A fighter aircraft.",
        "published_at": "2026-08-03T10:30:00",
        "procurement_method": "Open Tender",
    },
    {
        "id": "bel-2026-006",
        "title": "Radar Signal Processing Units & Secure Tactical Radios",
        "ministry": "Ministry of Defence",
        "department": "Defence Production",
        "organisation": "Bharat Electronics Limited (BEL)",
        "state": "Telangana",
        "categories": ["Defence", "Electronics", "Telecom", "Hardware"],
        "estimated_cost_lakhs": 650.0,
        "emd_lakhs": 13.0,
        "submission_deadline": "2026-09-10T17:00:00",
        "status": "active",
        "source": "BEL",
        "msme_eligible": True,
        "startup_eligible": True,
        "source_url": "https://bel-india.in/tenders",
        "source_tender_id": "BEL/HYD/RADAR/2026/12",
        "ai_summary": "Supply of software defined SDR tactical communication radios and FPGA radar signal processors.",
        "published_at": "2026-08-01T14:00:00",
        "procurement_method": "L1",
    },
    {
        "id": "ongc-2026-007",
        "title": "Offshore Rig Maintenance & Subsea Pipeline Inspection Services",
        "ministry": "Ministry of Petroleum and Natural Gas",
        "department": "Offshore Operations Division",
        "organisation": "Oil and Natural Gas Corporation (ONGC)",
        "state": "Gujarat",
        "categories": ["Energy", "Oil & Gas", "Services", "Infrastructure"],
        "estimated_cost_lakhs": 3400.0,
        "emd_lakhs": 68.0,
        "submission_deadline": "2026-10-05T15:00:00",
        "status": "active",
        "source": "ONGC",
        "msme_eligible": False,
        "startup_eligible": False,
        "source_url": "https://tenders.ongc.co.in",
        "source_tender_id": "ONGC/OFFSHORE/PIPE/2026/77",
        "ai_summary": "Comprehensive ROV inspection and cathodic protection maintenance for Mumbai High offshore platforms.",
        "published_at": "2026-07-28T16:00:00",
        "procurement_method": "Open Tender",
    },
    {
        "id": "bhel-2026-008",
        "title": "Ultra-Supercritical Boiler Tubes & Heavy Forgings Supply",
        "ministry": "Ministry of Heavy Industries",
        "department": "Power Equipment Group",
        "organisation": "Bharat Heavy Electricals Limited (BHEL)",
        "state": "Tamil Nadu",
        "categories": ["Power", "Manufacturing", "Heavy Engineering"],
        "estimated_cost_lakhs": 2100.0,
        "emd_lakhs": 42.0,
        "submission_deadline": "2026-09-18T16:30:00",
        "status": "active",
        "source": "BHEL",
        "msme_eligible": True,
        "startup_eligible": False,
        "source_url": "https://bhel.com/tenders",
        "source_tender_id": "BHEL/TRICHY/BOILER/2026/401",
        "ai_summary": "Procurement of alloy steel seamless boiler tubes for 800MW thermal expansion project.",
        "published_at": "2026-08-02T11:30:00",
        "procurement_method": "Open Tender",
    },
    {
        "id": "ntpc-2026-009",
        "title": "100MW Battery Energy Storage System (BESS) Integration",
        "ministry": "Ministry of Power",
        "department": "Renewable Energy Cell",
        "organisation": "NTPC Limited",
        "state": "Madhya Pradesh",
        "categories": ["Power", "Renewable Energy", "Electrical"],
        "estimated_cost_lakhs": 4500.0,
        "emd_lakhs": 90.0,
        "submission_deadline": "2026-10-12T17:00:00",
        "status": "active",
        "source": "NTPC",
        "msme_eligible": False,
        "startup_eligible": True,
        "source_url": "https://ntpctender.ntpc.co.in",
        "source_tender_id": "NTPC/RE/BESS/2026/09",
        "ai_summary": "Design, engineering, and commissioning of 100MW/400MWh grid-scale BESS for solar grid smoothing.",
        "published_at": "2026-08-01T15:00:00",
        "procurement_method": "QCBS",
    },
    {
        "id": "iocl-2026-010",
        "title": "Green Hydrogen Electrolyzer Unit 10MW Procurement",
        "ministry": "Ministry of Petroleum and Natural Gas",
        "department": "Refining & Marketing",
        "organisation": "Indian Oil Corporation Limited (IOCL)",
        "state": "Haryana",
        "categories": ["Energy", "Green Energy", "Oil & Gas"],
        "estimated_cost_lakhs": 2800.0,
        "emd_lakhs": 56.0,
        "submission_deadline": "2026-09-25T15:00:00",
        "status": "active",
        "source": "IOCL",
        "msme_eligible": True,
        "startup_eligible": True,
        "source_url": "https://iocletenders.nic.in",
        "source_tender_id": "IOCL/PANIPAT/GREEN-H2/2026",
        "ai_summary": "PEM electrolyzer stack supply for green hydrogen generation at Panipat Refinery.",
        "published_at": "2026-08-03T09:00:00",
        "procurement_method": "Open Tender",
    },
    {
        "id": "pwd-mah-2026-011",
        "title": "Construction of 6-Lane Elevated Expressway Corridor",
        "ministry": "Public Works Department",
        "department": "Highways & Bridges Division",
        "organisation": "Maharashtra PWD",
        "state": "Maharashtra",
        "categories": ["Civil", "Construction", "Infrastructure", "Roads"],
        "estimated_cost_lakhs": 18500.0,
        "emd_lakhs": 370.0,
        "submission_deadline": "2026-10-30T17:00:00",
        "status": "active",
        "source": "State PWD",
        "msme_eligible": False,
        "startup_eligible": False,
        "source_url": "https://mahapwd.gov.in",
        "source_tender_id": "PWD/PUNE/ELEVATED/2026/11",
        "ai_summary": "EPC contract for 12.4 km elevated flyover corridor with pre-stressed concrete girders.",
        "published_at": "2026-07-25T10:00:00",
        "procurement_method": "L1",
    },
    {
        "id": "pwd-up-2026-012",
        "title": "Widening & Asphalt Paving of State Highway 44",
        "ministry": "Public Works Department",
        "department": "Roads & Maintenance Division",
        "organisation": "Uttar Pradesh PWD",
        "state": "Uttar Pradesh",
        "categories": ["Civil", "Construction", "Roads"],
        "estimated_cost_lakhs": 3200.0,
        "emd_lakhs": 64.0,
        "submission_deadline": "2026-09-12T16:00:00",
        "status": "active",
        "source": "State PWD",
        "msme_eligible": True,
        "startup_eligible": False,
        "source_url": "https://uppwd.gov.in",
        "source_tender_id": "UPPWD/SH44/WIDENING/2026/88",
        "ai_summary": "4-laning and bituminous macadam resurfacing of 45 km stretch on Lucknow-Kanpur state highway.",
        "published_at": "2026-08-02T14:00:00",
        "procurement_method": "Open Tender",
    },
    {
        "id": "aiims-2026-013",
        "title": "High-End MRI Scanners & Robotic Surgical Systems Procurement",
        "ministry": "Ministry of Health and Family Welfare",
        "department": "Medical Equipment Procurement Division",
        "organisation": "AIIMS New Delhi",
        "state": "Delhi",
        "categories": ["Healthcare", "Medical Equipment", "Hardware"],
        "estimated_cost_lakhs": 5200.0,
        "emd_lakhs": 104.0,
        "submission_deadline": "2026-10-15T15:00:00",
        "status": "active",
        "source": "Autonomous Body",
        "msme_eligible": True,
        "startup_eligible": True,
        "source_url": "https://aiims.edu/tenders",
        "source_tender_id": "AIIMS/ND/EQUIP/3T-MRI/2026",
        "ai_summary": "Procurement of 3T Digital MRI Machines and dual-console Robotic Surgery Platforms with 5-year CMC.",
        "published_at": "2026-08-01T11:00:00",
        "procurement_method": "QCBS",
    },
    {
        "id": "iitb-2026-014",
        "title": "High Performance GPU Supercomputing Cluster (5 Petaflops)",
        "ministry": "Ministry of Education",
        "department": "Computer Science & Engineering",
        "organisation": "IIT Bombay",
        "state": "Maharashtra",
        "categories": ["IT", "AI", "Cloud", "Hardware"],
        "estimated_cost_lakhs": 2400.0,
        "emd_lakhs": 48.0,
        "submission_deadline": "2026-09-22T17:00:00",
        "status": "active",
        "source": "Autonomous Body",
        "msme_eligible": True,
        "startup_eligible": True,
        "source_url": "https://iitb.ac.in/tenders",
        "source_tender_id": "IITB/CSE/HPC-GPU/2026/02",
        "ai_summary": "AI supercomputer cluster with NVIDIA H100 GPUs and 100Gbps InfiniBand interconnect for LLM training.",
        "published_at": "2026-08-03T12:00:00",
        "procurement_method": "QCBS",
    },
    {
        "id": "bmc-2026-015",
        "title": "Automated Waste Processing & Bio-Methanation Plant 500 TPD",
        "ministry": "Urban Development Department",
        "department": "Solid Waste Management",
        "organisation": "Brihanmumbai Municipal Corporation (BMC)",
        "state": "Maharashtra",
        "categories": ["Smart City", "Infrastructure", "Renewable Energy", "Services"],
        "estimated_cost_lakhs": 4800.0,
        "emd_lakhs": 96.0,
        "submission_deadline": "2026-10-08T16:00:00",
        "status": "active",
        "source": "Municipal Corporation",
        "msme_eligible": True,
        "startup_eligible": True,
        "source_url": "https://portal.mcgm.gov.in",
        "source_tender_id": "BMC/SWM/BIOMETH/2026/15",
        "ai_summary": "DBOT contract for 500 tons per day organic waste dry anaerobic digestion bio-CNG facility.",
        "published_at": "2026-08-02T10:00:00",
        "procurement_method": "Open Tender",
    },
    {
        "id": "dmrc-2026-016",
        "title": "Metro Rolling Stock Automated Fare Collection (AFC) Gate Upgrade",
        "ministry": "Ministry of Housing and Urban Affairs",
        "department": "Signaling & Telecom Division",
        "organisation": "Delhi Metro Rail Corporation (DMRC)",
        "state": "Delhi",
        "categories": ["Railways", "Smart City", "Mobility", "IoT"],
        "estimated_cost_lakhs": 1550.0,
        "emd_lakhs": 31.0,
        "submission_deadline": "2026-09-18T15:00:00",
        "status": "active",
        "source": "DMRC",
        "msme_eligible": True,
        "startup_eligible": True,
        "source_url": "https://delhimetrorail.com/tenders",
        "source_tender_id": "DMRC/AFC/NCMC-QR/2026/04",
        "ai_summary": "Implementation of NCMC National Common Mobility Card & UPI QR-code gate readers across Phase 4 stations.",
        "published_at": "2026-08-01T13:00:00",
        "procurement_method": "QCBS",
    },
    {
        "id": "bbmp-2026-017",
        "title": "Smart LED Streetlighting & Command Center Operations (ICCC)",
        "ministry": "Urban Development Department",
        "department": "Electrical & Smart City Division",
        "organisation": "BBMP Bengaluru",
        "state": "Karnataka",
        "categories": ["Smart City", "Electrical", "IoT", "Services"],
        "estimated_cost_lakhs": 1950.0,
        "emd_lakhs": 39.0,
        "submission_deadline": "2026-09-14T17:00:00",
        "status": "active",
        "source": "Municipal Corporation",
        "msme_eligible": True,
        "startup_eligible": True,
        "source_url": "https://bbmp.gov.in/tenders",
        "source_tender_id": "BBMP/SMART-LIGHTING/2026/89",
        "ai_summary": "Conversion of 85,000 streetlights to smart dimmable LED fixtures integrated with Centralized ICCC platform.",
        "published_at": "2026-08-02T16:00:00",
        "procurement_method": "Open Tender",
    },
    {
        "id": "gail-2026-018",
        "title": "Cross-Country Natural Gas Pipeline SCADA & Leak Detection",
        "ministry": "Ministry of Petroleum and Natural Gas",
        "department": "Pipeline Project Group",
        "organisation": "GAIL (India) Limited",
        "state": "Rajasthan",
        "categories": ["Energy", "Oil & Gas", "IoT", "Software"],
        "estimated_cost_lakhs": 1400.0,
        "emd_lakhs": 28.0,
        "submission_deadline": "2026-09-26T15:00:00",
        "status": "active",
        "source": "GAIL",
        "msme_eligible": True,
        "startup_eligible": True,
        "source_url": "https://gailtenders.in",
        "source_tender_id": "GAIL/SCADA/GAS-LINE/2026",
        "ai_summary": "Acoustic leak detection system and SCADA telecommunication telemetry for 320 km gas pipeline.",
        "published_at": "2026-08-03T11:00:00",
        "procurement_method": "Open Tender",
    },
    {
        "id": "hpcl-2026-019",
        "title": "Refineries Automation & Cyber Security Operations Center (CSOC)",
        "ministry": "Ministry of Petroleum and Natural Gas",
        "department": "Information Security Cell",
        "organisation": "Hindustan Petroleum Corporation (HPCL)",
        "state": "Andhra Pradesh",
        "categories": ["Cybersecurity", "IT", "Software"],
        "estimated_cost_lakhs": 980.0,
        "emd_lakhs": 19.6,
        "submission_deadline": "2026-09-12T16:00:00",
        "status": "active",
        "source": "HPCL",
        "msme_eligible": True,
        "startup_eligible": True,
        "source_url": "https://hindustanpetroleum.com/tenders",
        "source_tender_id": "HPCL/CSOC/VISAKH/2026/07",
        "ai_summary": "24/7 Managed SIEM/SOAR Cybersecurity Operations Center for Visakh Refinery Industrial Control Systems.",
        "published_at": "2026-08-02T13:00:00",
        "procurement_method": "QCBS",
    },
    {
        "id": "gem-2026-020",
        "title": "Cloud Data Center Migration & Disaster Recovery Managed Services",
        "ministry": "Ministry of Electronics and Information Technology",
        "department": "National Informatics Centre",
        "organisation": "Government e-Marketplace (GeM)",
        "state": "Delhi",
        "categories": ["Cloud", "IT", "Services"],
        "estimated_cost_lakhs": 3600.0,
        "emd_lakhs": 72.0,
        "submission_deadline": "2026-10-02T17:00:00",
        "status": "active",
        "source": "GeM",
        "msme_eligible": True,
        "startup_eligible": True,
        "source_url": "https://gem.gov.in/tenders/gem-2026-020",
        "source_tender_id": "GEM/2026/B/991024",
        "ai_summary": "MeitY empanelled Cloud Service Provider (CSP) migration for GeM 4.0 portal infrastructure with RPO < 15 mins.",
        "published_at": "2026-08-03T14:00:00",
        "procurement_method": "QCBS",
    },
]
